# Generated by Django 3.1.3 on 2020-12-26 11:38

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201226_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, upload_to=recipes.models.get_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ingredients', to='recipes.unit', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=recipes.models.get_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Описание'),
        ),
    ]
