# Generated by Django 3.1.3 on 2020-12-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201226_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Время приготовления'),
        ),
    ]
