# Generated by Django 3.1.3 on 2021-01-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Ингредиент'),
        ),
    ]
